name: Lab 1 Deploy to Azure VM

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Running Java ${{ matrix.java }} compile
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.15
        uses: actions/setup-java@v1
        with:
          java-version: 1.15
      - name: Compile code
        run: ./gradlew build

  deploy:
    runs-on: ubuntu-latest
    name: Deploy the JAR file to the remote server
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.15
        uses: actions/setup-java@v1
        with:
          java-version: 1.15
      - name: Generate the package
        run: ./gradlew build
      - name: Deploy the package to the remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "build/libs/int493-software-arch-0.0.1-SNAPSHOT.jar"
          target: "lab1"
      - name: Run a script on remote server (start the application)
        if: always()
        uses: fifsky/ssh-action@master
        with:
          command: nohup java -jar int493-software-arch-0.0.1-SNAPSHOT.jar > /dev/null &
          host: ${{ secrets.HOST }}
          user: ${{ secrets.SSH_USER }}
          pass: ${{ secrets.SSH_PASSWORD }}
          args: "-tt"